version: '2.2'
services:
  goapp:
    image: gocovenant:v0.1
    depends_on:
      database:
        condition: service_healthy
    ports:
      - 8000:8000
    environment:
      DB_NAME: covenant_db
      DB_HOST: 172.20.128.1
      DB_PORT: 5432
      DB_USER: covenant_user
      DB_PSWD: testpass
    networks:
      static-network:
        ipv4_address: 172.20.128.2
  database:
    image: postgres
    volumes:
      - $HOME/docker:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      static-network:
        ipv4_address: 172.20.128.1
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
          ip_range: 172.28.5.0/24
