version: '3.7'
services:
  goapp:
    image: gocovenant
    ports:
      - 8000:8000
    environment:
      DB_NAME: covenant_db
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: covenant_user
      DB_PSWD: testpass
  database:
    image: covenant_db
    volumes:
      - psql_volume:/var/lib/postgresql/data
    ports:
      - 5432:5432

volumes:
  psql_volume:
